ktor:
  application:
    modules:
      - com.github.pedroluis02.authjwt.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  domain: "http://localhost"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "$SECRET"
